const invoice = {
   id: "5df3180a09ea16dc4b95f910",
   company: "Martin Dow Marker Limited (Formerly Merck Pvt. Ltd)",
   phone: "Ph # +92 21 111 523 523",
   address: "7, Jail Road Quetta Pakistan",
   PFINo: "PFI-18-0373",
   invoiceNo: "INV-18-0373",
   date: "Aug 02, 2018",
   currency: "EUR",
   country: "USA",
   shippingTerms: "CFR by SEA",
   paymentTerms: "Bank Contract",
   landingPort: "USA",
   destinationPort: "Karachi",
   preparedBy: "Fawad Ahmed",
   bankDetails: {
      accountTitle: "AdChem FZE",
      IBAN: "AE140240097521214845701",
      address: "Emaar Business Park, Sh.Zayed Road, Dubai, United Arab",
      name: "DUBAI ISLAMIC BANK (EURO)",
      swiftCode: "DUIBAEAD",
      currency: "EUR",
   },
   footerRows: [
      "23978009 15.03.2018 15.03.2021",
      "23978009 15.03.2018 15.03.2021",
      "23978009 15.03.2018 15.03.2021",
      "23978009 15.03.2018 15.03.2021",
   ],
   tableData: {
      totalString: "Thirty Two Thousand Nine Hundred Forty only",
      currency: "EUR",
      total: 32940.0,
      rows: [
         {
            name: "Ferrous Gluconate EP Powder",
            description: "In very fine Powder form",
            hashCode: "2918.16.0000",
            qty: 5400,
            uom: "KG",
            unitPrice: 6.1,
            totalAmount: 32940,
            sn: 1,
         },
         {
            name: "Ferrous Gluconate EP Powder",
            description: "In very fine Powder form",
            hashCode: "2918.16.0000",
            qty: 3800,
            uom: "KG",
            unitPrice: 3,
            sn: 2,
         },
         {
            name: "Ferrous Gluconate EP Powder",
            description: "In very fine Powder form",
            hashCode: "2918.16.0000",
            qty: 242,
            uom: "KG",
            unitPrice: 3,
            sn: 3,
         },
         {
            name: "Ferrous Gluconate EP Powder",
            description: "In very fine Powder form",
            hashCode: "2918.16.0000",
            qty: 431,
            uom: "KG",
            unitPrice: 3,
            sn: 4,
         },
         {
            name: "Ferrous Gluconate EP Powder",
            description: "In very fine Powder form",
            hashCode: "2918.16.0000",
            qty: 3800,
            uom: "KG",
            unitPrice: 3,
            sn: 5,
         },
         {
            name: "Ferrous Gluconate EP Powder",
            description: "In very fine Powder form",
            hashCode: "2918.16.0000",
            qty: 3800,
            uom: "KG",
            unitPrice: 3,
            sn: 6,
         },
         {
            name: "Ferrous Gluconate EP Powder",
            description: "In very fine Powder form",
            hashCode: "2918.16.0000",
            qty: 3800,
            uom: "KG",
            unitPrice: 3,
            sn: 7,
         },
         //{
         //   name: "Ferrous Gluconate EP Powder",
         //   description: "In very fine Powder form",
         //   hashCode: "2918.16.0000",
         //   qty: 3800,
         //   uom: "KG",
         //   unitPrice: 3,
         //   sn: 2,
         // },{
         //   name: "Ferrous Gluconate EP Powder",
         //   description: "In very fine Powder form",
         //   hashCode: "2918.16.0000",
         //   qty: 3800,
         //   uom: "KG",
         //   unitPrice: 3,
         //   sn: 2,
         // },{
         //   name: "Ferrous Gluconate EP Powder",
         //   description: "In very fine Powder form",
         //   hashCode: "2918.16.0000",
         //   qty: 3800,
         //   uom: "KG",
         //   unitPrice: 3,
         //   sn: 2,
         // },{
         //   name: "Ferrous Gluconate EP Powder",
         //   description: "In very fine Powder form",
         //   hashCode: "2918.16.0000",
         //   qty: 3800,
         //   uom: "KG",
         //   unitPrice: 3,
         //   sn: 2,
         // },{
         //   name: "Ferrous Gluconate EP Powder",
         //   description: "In very fine Powder form",
         //   hashCode: "2918.16.0000",
         //   qty: 3800,
         //   uom: "KG",
         //   unitPrice: 3,
         //   sn: 2,
         // },{
         //   name: "Ferrous Gluconate EP Powder",
         //   description: "In very fine Powder form",
         //   hashCode: "2918.16.0000",
         //   qty: 3800,
         //   uom: "KG",
         //   unitPrice: 3,
         //   sn: 2,
         // },{
         //   name: "Ferrous Gluconate EP Powder",
         //   description: "In very fine Powder form",
         //   hashCode: "2918.16.0000",
         //   qty: 3800,
         //   uom: "KG",
         //   unitPrice: 3,
         //   sn: 2,
         // },{
         //   name: "Ferrous Gluconate EP Powder",
         //   description: "In very fine Powder form",
         //   hashCode: "2918.16.0000",
         //   qty: 3800,
         //   uom: "KG",
         //   unitPrice: 3,
         //   sn: 2,
         // },
      ],
   },
};

export default invoice;
